---
- name: "test for swap partition"
  shell: 'sudo swapon -s | grep -E "^/"'
  register: swapfile
  ignore_errors: yes

- name: "write swapfile"
  when: swapfile|failed
  command: fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
  register: write_swapfile

- name: "set swapfile permissions"
  when: swapfile|failed and write_swapfile.changed
  file: path={{ swapfile_location }}
        owner=root
        group=root
        mode=0600

- name: "prepare swapfile"
  when: swapfile|failed and write_swapfile.changed
  command: "mkswap {{ swapfile_location }}"

- name: "enable swap"
  when: swapfile|failed
  command: "swapon {{ swapfile_location }}"

- name: "add swapfile mount point"
  when: swapfile|failed
  lineinfile: dest=/etc/fstab
              regexp="^{{ swapfile_location }}"
              state=present
              line="{{ swapfile_location }}       none    swap    sw      0       0"

- name: "set swappiness"
  when: swapfile|failed
  sysctl: name=vm.swappiness
          value={{ swapfile_swappiness }}
          state=present

- name: "set vfs cache pressure"
  when: swapfile|failed
  sysctl: name=vm.vfs_cache_pressure
          value={{ swapfile_vfs_cache_pressure }}
          state=present
